### ISSUE TITLE
N: CEQR transportation data

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#108]
Goal: close issues 2 and 3 here
https://gitlab.com/nycplanning/ceqr-app-data/issues

- [x] Close issue #2 and deliver to @pichot by end of week 1 (@baolingz)
- [ ] Close issue #3 and deliver by end of sprint
- [ ] Give output of issue #3 to @croswell81 and @pichot will point him to metadata

**Comment by AmandaDoyle** [comment]
@baolingz Completed task one in the first week and delivered to @pichot 
@bendnorman worked on issue 3 and is almost done
