### ISSUE TITLE
O: CEQR Transportation data

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#122]
Goal: close issue 3 here
https://gitlab.com/nycplanning/ceqr-app-data/issues

- [x]   Confirm issue #2 is complete with @pichot (@baolingz)
- [x]   Close issue #3 and deliver asap
- [ ]   Give output of issue #3 to @croswell81 and @pichot will point him to metadata

**Comment by AmandaDoyle** [comment]
issue #3: Generated transportation zones.  Need to deliver to GIS to publish
issue #2: corrected missing census tracts and republished
