### ISSUE TITLE
Y: PLUTO research

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#315]
**Tasks to complete during Sprint Y**
Ordered by priority but may not be able to execute them in the exact order

- [ ] Contribute to issue #308 by providing list of lots where the year built should be updated using LPC data (work with Amanda and Lynn)
- [x] Read Baiyue's blogs to get familiar with Geocoding  https://medium.com/nyc-planning-digital/tagged/data
- [x] Create a QAQC report that reports records with an extreme number of floors (i.e. 100 floors in Staten Island).  Output the subset of records to be researched.  Research will be done and corrections will be added to the pluto_input_research table (improvement: take outliers) 
- [x] Create a QAQC report that reports instances where  lot front x lot depth <> lot area but lot front x lot depth = shape area.  These are potentially records where the the shape area should be updated
- [x] Move 2 QAQC reports into Jupyter notebooks
- [ ] Work with Amanda to productionalize logic for flagging lots that are regular but should be irregular, updating the irregular lot code and the lot area
- [x] Slides for data users group meeting

**Backburner**
- [ ] Report instances where the Lot Area does not equal Lot Front x Lot Depth.  Research the most extreme cases and provide corrected values where possible by providing corrected data for each bbl.  Deliverable is to output a subset of the data that should be researched and then corrections can be inserted into the research table.  Can be run with each PLUTO update.
- [ ] Report instances where the building area, number of floors, and lot area are not aligned.  Research on how to best define what is aligned or not.  Deliverable is to output a subset of the data that should be researched and then corrections can be inserted into the research table.  Can be run with each PLUTO update.
- [ ] Recommend how to improve the accuracy and detail of the lot type attribute.  Deliverable is logic / algorithm to apply to PLUTO to identify these lots and update the lot type attribute.

**Comment by AmandaDoyle** [comment]
@annmorrisgis moved her work into Jupyter notebooks and made her processes able to fit in the production environment
