### ISSUE TITLE
Add ~800 park names to CSCL for DPR

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#410]
DPR sent a shapefile - "DPR_311_Sites" with 2136 records. Rodrigo ran it through and 1200 are already in Geo. 

- [ ] 675 names to add to SND
- [ ] 675 request the creation of commonplaces
- [x] 85 names exceed 32 bytes, recommend diff spelling and add to SND
- [ ] 85 associate over 32 byte spellings to commonplaces
- [ ] 21 single point cases, provide recommendation to DPR

**Comment by TomMCosta** [comment]
A second epic has been created for cleanup
