### ISSUE TITLE
Process BXBP backlog of address assignments (2002 to present)

### ISSUE THREAD

**Issue by TomMCosta** [NYCPlanning/edm-overview#425]
1960 items.

- [ ] Run backlog through Desktop 20A
- [ ] Review hits
- [ ] Research rejects and add to PAD and CSCL
- [ ] Request address points and footprints as needed

**Comment by TomMCosta** [comment]
Completed. New epic to be created for regeocoding against 20B and new 2020 applications.
