### ISSUE TITLE
K: DOB Milestones

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#49]
- [x] Send DOB a description of process
- [x] Process one weekly report
- [x] Send DOB a spreadsheet showing actions taken and questions that need answering
- [x] GEO adds TBINs to TPAD
- [ ] Updates move to public test (proposed date 6/10)
- [ ] Updates move to production (proposed date 6/14)

**Comment by TomMCosta** [comment]
Work completed, however comments for DOB need to be tweaked before Monday's meeting. Related work will continue in L sprint.
