### ISSUE TITLE
Maintenance: Secret management using GitHub API

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/edm-overview#499]
~~https://www.vaultproject.io/~~
https://developer.github.com/v3/actions/secrets/

**Comment by SPTKL** [comment]
https://developer.github.com/v3/actions/secrets/

instead of deploying vault, maybe we can just use the gihub actions API

**Comment by mgraber** [comment]
# Running Notes

## Tasks
- [ ] Figure out how to access secrets using API so we can use them when running our workflows in server rather than on GitHub actions
- [ ] Figure out how to add/change secrets using API
- [ ] Write workflow for routine changes to secrets across all of the data-engineering repos

### How to access GitHub API secrets from the command line
1. GitHub API does not allow ssh-based authentication. Instead, you must create a token. For instructions on how to create a token, [see this](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).
2. Export your token as an env variable: `export GITHUB_TOKEN='PutYouRToKenHeRe!'`
3. To make things easier, you might want to also export your username: `export GITHUB_USER='yourusername'`
4. You can use curl to interact with the GitHub API through the command line or one of our bash scripts.
    * For example, to list all of the secrets for a repo, run: `curl -sL --user "$GITHUB_USER:$GITHUB_TOKEN" GET "https://api.github.com/repos/NYCPlanning/db-something/actions/secrets"`
    * To get a specific secret, it would look like this: `curl -sL --user "$GITHUB_USER:$GITHUB_TOKEN" GET "https://api.github.com/repos/NYCPlanning/db-something/actions/secrets/SECRET_NAME"`

**Comment by SPTKL** [comment]
https://stedolan.github.io/jq/
parse json through command line using jq ^

**Comment by mgraber** [comment]
Consider using organization-level secrets for multiple repos, simplifying adding and changing without needing to use API to do so.
