### ISSUE TITLE
update labels in DE repos

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/edm-overview#861]
## motivation
- data engineering repos have many different and unused labels for issues and PRs
- reviewing, reducing, and standardizing labels will help track and communicate the status and details of work

## labels to use
- bug
- data update
- documentation
- enhancement
- maintenance
- needs data
- needs scoping
- question

## ideas
* use an existing github action from the marketplace to sync labels. favorites:
  * [Label Sync Action](https://github.com/marketplace/actions/label-sync-action): repo to repo using config file in this repo
  * [manage-your-labels](https://github.com/marketplace/actions/manage-your-labels): org to repo using a [default community health files repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) named `.github`
* use org-level variables to list repos

## todo
- [x] draft a list of labels
- [x] update template repo to use draft list
- [x] get feedback from DE team
- [x] use [labels in template repo](https://github.com/NYCPlanning/db-template-repo/issues/labels) as a staging area
- [x] make a list of relevant repos
- [ ] apply label list to repos

**Comment by damonmcc** [comment]
hey @fvankrieken, here's the issue I made about repo tags. might be a good place to write ideas / findings

**Comment by damonmcc** [comment]
common tags that seem worth using:
- bug
- enhancement
- documentation
- question
- maintenance

potential DCP Date Engineering tags:
- data update
- waiting for data

**Comment by fvankrieken** [comment]
Currently, we have in use the following:
- 'good to go'
- 'data: ingestion'
- 'dataloading'
- 'wip'
- 'dependencies'
- 'decennial'
- 'corrections'
- 'qaqc'
- 'research'
- 'metadata'
- 'documentation'
- 'QAQC'
- 'help wanted'
- 'future'
- 'wontfix'
- 'bug'
- 'data update'
- 'enhancement'
- 'question'
- 'priority'
- 'QA'
- 'Epic'
- 'priority: low'

basic plot with total counts of each. Happy to do breakdown by repo if that'd be useful, or whatever fun visualization you'd like
![image](https://user-images.githubusercontent.com/9454672/226930433-d8aba46a-f32f-4911-b466-cf6b4f912e81.png)

**Comment by fvankrieken** [comment]
Spent a little more time than I would have liked on this but had to finish.

Axis is percentage of issues in that repo with this label

![image](https://user-images.githubusercontent.com/9454672/226941531-e868a3a9-3944-4eea-83bc-f10758bddc5d.png)

**Comment by damonmcc** [comment]
@fvankrieken
nice! kinda seems like the most popular tags (enhancement, data update, question) are ones I imagined we'd wanna use

side note: if u wanna share the code you've written to use the github API, I'd love to see your approaches before I mess around. the [edm-sandbox](https://github.com/NYCPlanning/edm-sandbox) repo might be a good place to put random code, but anyway of sharing works for me

**Comment by jackrosacker** [comment]
I'm very interested to see the tag list you end up using for DE. May be some valuable cross over for GIS repos.
@caseysmithpgh
