### ISSUE TITLE
2023 Open Data Compliance Plan

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#927]
Completing your agency’s Open Data Annual Reporting Workbook 

  - [x] Download the 2023 NYC Open Data Annual Report workbook from the Open Data Coordinator resources page 
         (https://opendata.cityofnewyork.us/open-data-coordinators/).
    - Review the workbook’s “Instructions” tab. For additional guidance, consult our [annotated sample workbook ](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fopendata.cityofnewyork.us%2Fwp-content%2Fuploads%2FANNOTATED_SAMPLE_NYC_OpenDataAnnualReportWorkbook.xlsx&data=05%7C01%7Cmcroswe%40planning.nyc.gov%7C08b7e864404047b365ed08db57d99e5a%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638200366295337718%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I4Mmycki9s0QngWRdWj7Be4Xtadz%2B9K%2FDI34W2IEaFU%3D&reserved=0)which contains some errors we commonly see and best practices for each tab.
>
  - [x] By **Wednesday, May 24**, confirm receipt of this workbook and report any initial errors to opendata@oti.nyc.gov.
>
  - [x] Review and complete the workbook’s tabs.
      - [x] A. Future Releases
      - [x] B.  Website Data
      - [x] C. FOIL   
 
     - Note that each of these tabs contains two separate tables that will need to be reviewed and completed, though not every table will apply to every agency. Each tab also contains further guidance on how to fill out these tables.
>
 - [x] Fill out the new [Civic Engagement Activity](https://airtable.com/shrYCsovyUjhb1EGV) form to share how your agency engaged the public around Open Data. You will receive a confirmation email with your responses once this is completed. 
 
    - Note that if you already submitted engagement activities for this reporting period, you do not need to reenter the same activities into this new form. Anyone who already entered civic engagement activities for this reporting period can find them listed in this [table grouped by agency](https://airtable.com/shrIMbUHr0D0cnT12/tblekupL43qzSZ3HS).
>
  - [x] Review the completed workbook with your agency’s leadership, and have your general counsel certify its contents using 2023 General Counsel Certification
>
  - [x] Before **EOD, Friday, June, 30**, submit the Annual Reporting Workbook and General Counsel Certification using the [Open Data Annual Report submission form](https://opendata.cityofnewyork.us/wp-content/uploads/AGENCY_NYC_OpenDataAnnualReport_GeneralCounselCertification2023.pdf)
    - Note that any workbooks **submitted on or before Friday, June 16** or before will be prioritized for our feedback and review so you can be done with this process early.

**Comment by croswell81** [comment]
Sent to counsel on 6/27/23. Susan is OOO until 7/3 so check in with Alison if not received by 6/29.
