### ISSUE TITLE
Update Scheduled Task info to reflect 10.8 py2 interpreter

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/edm-overview#965]
### Summary:
Upgrading to ArcMap 10.8.2 from 10.6 means that for each scheduled script that uses python2, the path to the python 2 interpreter referenced in Task Scheduler meta files must be updated from "C:\Python27\ArcGIS**10.6**\python.exe" to "C:\Python27\ArcGIS**10.8**\python.exe"

### TODOs:

- [x] Update the XML templates for each relevant scheduled task to point to the ArcGIS 10.8 interpreter listed above. See photo for confirmation. Note that each XML highlighted has had the interpreter path updated in the XML. A few others use python 2 but are called by a batch file. These have been updated and require no addtl. user action:
![image.png](https://images.zenhubusercontent.com/63c70f3233c7931e09b40a81/ba5f591a-d359-40f7-8abc-9df865efa743)
- [x] @croswell81 :: Re-import the XMLs highlighted above into Task Scheduler on your machine
- [x] @jackrosacker :: Re-import the XMLs highlighted above into Task Scheduler on your machine
- [x] @caseysmithpgh :: Re-import the XMLs highlighted above into Task Scheduler on your machine

**Comment by croswell81** [comment]
@jackrosacker Confirming all tasks have been updated and I just need to re-Import

**Comment by jackrosacker** [comment]
@croswell81 that is correct. All task templates and batch files _should_ be fully updated

**Comment by croswell81** [comment]
@jackrosacker I imported all tasks. Feel free to close if all items are completed.
