### ISSUE TITLE
Update Inclusionary Housing with Corrections BK02

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#982]
This Helpscout issue 2934 was completed by a duplicate Open Data Screendoor ticket 10054

### Tasks:
- [x] confirm discrepancy between BoBA/PROD FCs and Appendix F drawings
- [x] Confirm adjustments with Paul Power
- [x] Update FC drawings
- [x] Publish to BoBA
- [x] Update Open_Data.xlsx tracker
- [x] Publish to OpenData
- [x] Publish to AGO
- [x] Publish to DO

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBait6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--075a4863ee97aa836aa875776a2d9b7d5f238c6f/image.png)
